### ISSUE TITLE
error when fine-tuning

### ISSUE THREAD

**Issue by JoeyHeisenberg** [jik876/hifi-gan#10]
I want to use FastSpeech 2 + hifigan, but it sound a little nosie in some generated audios, so I get the generate mel-spectrogram from FastSpeech 2 to retrain the hifigan, BUT MEET the error when fine-tuning

`Loading 'cp_hifigan/g_00320000'
Complete.
Loading 'cp_hifigan/do_00320000'
Complete.
Epoch: 1227
Traceback (most recent call last):
  File "train.py", line 286, in <module>
    main()
  File "train.py", line 280, in main
    mp.spawn(train, nprocs=h.num_gpus, args=(a, h,))
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/data/glusterfs_speech_tts_v2/public_data/tts_public_data/11104653/vocoder/hifi-gan/train.py", line 113, in train
    for i, batch in enumerate(train_loader):
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 84, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 84, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [8192] at entry 0 and [6712] at entry 10`

**Comment by JoeyHeisenberg** [comment]
another question, when fine-tuning, we use the generated mel-spectrogram and the ground truth audio to retrain the hifigan, the length of generated mel-spectrogram may not match the length of the ground truth mel-spectrogram, will it cause any troubles when fine-tuning? Or am I having some misunderstandings on teacher-force?

**Comment by CookiePPP** [comment]
> the length of generated mel-spectrogram may not match the length of the ground truth mel-spectrogram

You are correct, when teacher forcing they should be the exact same length. The 0th frame is predicted using zeros as input, and every other frame is generated using teacher-forced inputs.
If you're [predicting more than 1](https://github.com/NVIDIA/tacotron2/blob/master/hparams.py#L56) frame per decoder step then there might be a difference in length of 1/2 frame, but otherwise the length should be identical for generated spectrograms.

**Comment by CookiePPP** [comment]
Oh right, and FastSpeech2 doesn't have teacher-forcing cause it's not autoregressive.

**Comment by JoeyHeisenberg** [comment]
Sounds great! I will try to use the ground-truth message to get the mel-spectrogram, Thx @CookiePPP   : )

**Comment by jik876** [comment]
@JoeyHeisenberg 

Perhaps the reason is that the lengths of the input data are different. It would be nice to check whether the length of the ground truth and the input condition are the same.

**Comment by jik876** [comment]
I close this as there are no recent updates. Please reopen if you need additional comments.

**Comment by yt605155624** [comment]
hi, could you please tell me which  implementation of FastSpeech 2 are you using?

**Comment by JoeyHeisenberg** [comment]
> hi, could you please tell me which implementation of FastSpeech 2 are you using?

I think espnet or TensorTTS is fine, you can try either of them, actually I code based on this two projects

**Comment by debasish-mihup** [comment]
@JoeyHeisenberg How did you manage to use hifigan vocoder with Fastspeech 2 generated Mels? can you share the normalization steps required to convert the fastspeech 2 generated mels to work with this repo trained vocoder?

**Comment by v-nhandt21** [comment]
@debasish-mihup @yt605155624 @JoeyHeisenberg @jik876  I have the same problem when run fine tuning using teacher force from tacotron2 and fastspeech2

The teacher force mel spectrogram has one more frame compare to the one when generate with librosa from ground truth audio. Have you all handle this miss-match. Should I remove the "The 0th frame" of Mel spectrogram from fastspeech2
