### ISSUE TITLE
pickle.UnpicklingError: invalid load key, '{'

### ISSUE THREAD

**Issue by rafa6g** [jik876/hifi-gan#123]
I made a Google Colab notebook following this repo's intructions, but when I try to execute `inference.py` with the pretrained model LJ_FT_T2_V3, it gives me an error:

```
Initializing Inference Process..
Loading 'config.json'
Traceback (most recent call last):
  File "inference.py", line 94, in <module>
    main()
  File "inference.py", line 90, in main
    inference(a)
  File "inference.py", line 40, in inference
    state_dict_g = load_checkpoint(a.checkpoint_file, device)
  File "inference.py", line 20, in load_checkpoint
    checkpoint_dict = torch.load(filepath, map_location=device)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 692, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '{'.
```

Anyone how to solve it?

**Comment by rafa6g** [comment]
Sorry, I was executing the wrong code:
`!python inference.py --checkpoint_file config.json`
Then I tried with the correct one:
`!python inference.py --checkpoint_file generator_v3`
My mistake.

**Comment by mepc36** [comment]
Could I get access to your Colab notebook please @rafa6g ?
