### ISSUE TITLE
when fine_tuning with the tacotron2 model to produce mel_**.npy, a RuntimeError happened.

### ISSUE THREAD

**Issue by yBeOne** [jik876/hifi-gan#34]
Traceback (most recent call last):
  File "train.py", line 272, in <module>
    main()
  File "train.py", line 268, in main
    train(0, a, h)
  File "train.py", line 113, in train
    for i, batch in enumerate(train_loader):
  File "/home/.conda/envs/yzh/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/.conda/envs/yzh/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/.conda/envs/yzh/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/.conda/envs/yzh/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/.conda/envs/yzh/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/.conda/envs/yzh/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/.conda/envs/yzh/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/hifi/meldataset.py", line 163, in __getitem__
    center=False)
  File "/data/hifi/meldataset.py", line 50, in mel_spectrogram
    if torch.min(y) < -1.:
RuntimeError: invalid argument 1: cannot perform reduction function min on tensor with no elements because the operation does not have an identity at /pytorch/aten/src/TH/
generic/THTensorEvenMoreMath.cpp:345

**Comment by jik876** [comment]
I recommend you check what value is inputted for 'audio' argument at line 161 in `meldataset.py`.

**Comment by jik876** [comment]
I close this as there are no recent updates. Please reopen if anyone needs additional comments.
