### ISSUE TITLE
RuntimeError when finetuning the model

### ISSUE THREAD

**Issue by Charlottecuc** [jik876/hifi-gan#49]
Hi. Thank you very much for your implementation.
I extracted mels following the instructions. The frame size of the mels and audios is matched.
However, when I tried to finetune hifi-gan, I still got the following problem.
Could you tell me how to solve this? Thank you very much!

```
    main()
  File "train.py", line 267, in main
    train(0, a, h)
  File "train.py", line 113, in train
    for i, batch in enumerate(train_loader):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 79, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 79, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 118 and 167 in dimension 1 at /opt/conda/conda-bld/pytorch_1579027003190/work/aten/src/TH/generic/THTensor.cpp:612
```

**Comment by Miralan** [comment]
It seems like that the mels of one batch have different shape, such as [118, 80] and [167, 80], so make sure they have same shape(mel shape should be [80, T]).  And you can also check line 150-160 in meldataset.py (self.split is True), just print mel.shape at the end of \__getitem\__() to check it.

**Comment by Charlottecuc** [comment]
@Miralan Thank you! Solved. Yes, the shape should be [80, T], not [T, 80].
